// VKey - Localized String Dictionary (English translations)
// Vietnamese is the default language (text in HTML), only English needs mapping.
// Keys match data-i18n attributes in HTML elements.

var STRINGS = {
    en: {
        // ── Common (shared across dialogs) ──
        "close": "Close",
        "add": "+ Add",
        "delete": "- Delete",
        "application": "Application",
        "refresh_list": "Refresh list",
        "pick_window": "\uD83C\uDFAF Pick window",
        "excluded_apps_title": "Lock mode per app (E / V)",
        "tsf_apps_title": "TSF Apps",
        "no_apps_found": "No applications found",
        "no_matching": "No matching results",
        "no_running_apps": "No running applications",

        // ── Settings dialog ──
        "s.pin": "Pin to top",
        "s.admin_running": "Running as Administrator",
        "s.input_method": "Input Method",
        "s.user_defined": "User-defined",
        "s.code_table": "Code Table",
        "s.switch_key": "Switch Key",
        "s.switch_key_title": "Switch key",
        "s.beep": "Beep Sound",
        "s.beep_tooltip": "Play sound when switching language",
        "s.smart_switch": "Smart app exclusion",
        "s.smart_switch_tooltip": "Auto-remember input mode per app",
        "s.enable_exclude": "Lock E/V mode per app",
        "s.list": "List",
        "s.exclude_tooltip": "Lock E or V typing mode for each application (disables hotkeys inside the app)",
        "s.cjk_auto_switch": "Auto-disable on CJK layout",
        "s.cjk_auto_switch_tooltip": "Switch to E when a Chinese/Japanese/Korean layout is active",
        "s.enable_tsf": "Use TSF for apps",
        "s.tsf_tooltip": "Use TSF engine instead of hook for listed apps",
        "s.advanced": "Advanced settings",
        "s.tab_input": "Input",
        "s.tab_macro": "Macro",
        "s.tab_system": "System",
        "s.tab_about": "About",

        // Tab 1: Input
        "s.modern_ortho": "New diacritics style (o\u00E0, u\u00FD)",
        "s.auto_caps": "Auto-capitalize first letter",
        "s.allow_zwjf": "Allow \"z w j f\" as initial consonants",
        "s.allow_zwjf_tooltip": "Allowed by default. Only needed when spell check is on",
        "s.spell_check": "Spell check",
        "s.restore_key": "Auto-restore keys on wrong word",
        "s.allow_english_bypass": "Allow English bypass (e.g. yes \u2192 \u00FDe)",
        "s.allow_english_bypass_tooltip": "Allow applying Vietnamese tone marks on English words or exceptions",
        "s.suggest_keep_chars": "BS keeps chars on suggest",
        "s.suggest_keep_chars_tooltip": "When dismissing a browser suggestion via Backspace, preserve typed chars. Warning: tone placement may be wrong if you keep typing right after BS.",
        "s.esc_restore_raw": "Esc restores raw keys",
        "s.esc_restore_raw_tooltip": "Press Esc while typing to undo Vietnamese conversion and keep raw keys (e.g. v\u00EDu \u2192 virus)",
        "s.spell_exclusions": "Spell exclusions",
        "s.spell_exclusions_tooltip": "Abbreviation prefixes that bypass spell check (e.g. h\u0111, \u0111p). Prefix match, min 2 chars.",
        "s.app_encoding": "Per-app / Clipboard",
        "s.config": "Configure",
        "s.temp_off_label": "Temp disable input",
        "s.temp_off_tooltip": "Choose key to temp-disable Vietnamese for current word. Note: Ctrl triggers on a single tap — may activate accidentally.",
        "s.temp_off_none": "Off",
        "s.temp_off_dup_alt": "Double Alt",
        "s.temp_off_ctrl": "Press Ctrl",

        // Tab 2: Macro
        "s.enable_macro": "Enable macro",
        "s.macro_english": "Use macro in English mode",
        "s.auto_caps_macro": "Auto-capitalize from macro",
        "s.quick_telex": "Quick double consonant",
        "s.quick_telex_tooltip": "cc=ch, gg=gi, kk=kh, nn=ng, qq=qu, pp=ph, tt=th, uu=ươ",
        "s.quick_start": "Quick start consonant",
        "s.quick_start_tooltip": "f\u2192ph, j\u2192gi, w\u2192qu",
        "s.quick_end": "Quick end consonant",
        "s.quick_end_tooltip": "g\u2192ng, h\u2192nh, k\u2192ch",
        "s.temp_off_macro": "Skip macro with Esc",
        "s.temp_off_macro_tooltip": "Press Esc before typing to skip macro for next word",
        "s.macro_table_btn": "Macro table...",

        // Tab 3: System
        "s.run_startup": "Run on Windows startup",
        "s.startup_mode": "Default mode",
        "s.startup_mode_v": "Vietnamese",
        "s.startup_mode_e": "English",
        "s.startup_mode_r": "Remember last",
        "s.show_startup": "Show settings on startup",
        "s.run_admin": "Run as Administrator",
        "s.desktop_shortcut": "Create desktop shortcut",
        "s.bg_opacity": "Background opacity",
        "s.icon_style": "Customize icon",
        "s.icon_style_color": "Default color",
        "s.icon_style_dark": "Dark",
        "s.icon_style_light": "Light",
        "s.icon_style_custom": "Custom",
        "s.icon_style_auto": "Auto",
        "s.english_ui": "English interface",
        "s.english_ui_tooltip": "Switch UI, menus, and notifications to English",
        "s.force_light_theme": "Always use light theme",
        "s.force_light_theme_tooltip": "Ignore Windows dark mode, always show light theme",
        "s.custom_colors": "Custom icon colors",
        "s.color_v": "Choose V color",
        "s.color_e": "Choose E color",
        "s.floating_icon": "Floating V/E icon",
        "s.floating_icon_tooltip": "Show floating icon. May reduce FPS in Fullscreen games (Borderless recommended)",
        "s.tsf_indicator": "Show \"T\" icon for TSF apps",
        "s.tsf_indicator_tooltip": "When an app uses TSF, show a \"T\" icon (red=V, blue=E) instead of the usual V/E icon. Turn off to always see V/E.",
        "s.debug_log": "Enable debug log",
        "s.debug_log_tooltip": "Write detailed log to a file you can attach when reporting bugs. File lives next to VKey.exe (VKey_*.log).",
        "s.open_log_folder": "Open log folder",
        "s.enable_toast": "Show notifications (toast)",
        "s.enable_toast_tooltip": "Show small notifications at the top when settings are changed or lists are modified.",

        // Tab 4: About
        "s.tagline": "Modern Vietnamese Input Method",
        "s.version_label": "Version:",
        "s.dev_label": "Author:",
        "s.origin_label": "Origin:",
        "s.origin_text": "Project inspired by OpenKey and VietType, aiming to improve the UI, engine, and add new features.",
        "s.license": "VKey is open-source, free, and non-profit software.",
        "s.auto_update": "Auto-check for updates",
        "s.check_now": "Check now",
        "s.update_tooltip": "Check for new version on startup",
        "s.sponsor_p1": "Free code signing on Windows provided by",
        "s.sponsor_p2": ", certificate by",

        // ── Restart banner (hybrid TSF DLL update) ──
        "update.banner.pending":    "Update not finished. Restart Windows to apply the new TSF version.",
        "update.banner.mismatch":   "Some apps still run the old version. Restart Windows to sync.",
        "update.banner.restartNow": "Restart now",
        "update.banner.later":      "Later",
        "update.banner.confirm":    "Restart Windows now to finish the VKey update?",
        "s.report_issue_label": "Are you having problems?",
        "s.report_issue": "Report problem",

        // ── Macro dialog ──
        "m.title": "Macro Table",
        "m.shortcut": "Shortcut",
        "m.shortcut_ph": "e.g.: btw",
        "m.content": "Full content",
        "m.content_ph": "e.g.: by the way",
        "m.import": "Import from file...",
        "m.export": "Export to file...",
        "m.edit": "+ Edit",
        "m.hint_enter": "Press Enter for a new line",
        "m.hint_clipboard": "Long macros use Clipboard to paste (current Clipboard content will be overwritten)",
        "m.trigger_keys": "Trigger keys:",
        "m.trigger_arrows": "Arrows",

        // ── Spell Exclusions dialog ──
        "se.info": "Abbreviation prefixes that bypass spell check. Prefix match, min 2 chars. E.g.: h\u0111 covers h\u0111, h\u0111t, h\u0111qt...",
        "se.exclusion_list": "Exclusion list",
        "se.word": "Word",

        // ── Excluded Apps dialog ──
        "ea.app_ph": "e.g.: notepad.exe",
        "ea.excluded_list": "Excluded applications",
        "ea.browse": "📁 Browse .exe...",
        "ea.import": "Import from file...",
        "ea.export": "Export to file...",

        // ── TSF Apps dialog ──
        "tsf.app_ph": "e.g.: notepad.exe",
        "tsf.app_list": "TSF applications",
        "tsf.import": "Import from file...",
        "tsf.export": "Export to file...",

        // ── Convert Tool dialog ──
        "ct.title": "Convert Tool",
        "ct.general": "General Options",
        "ct.to_upper": "Convert to UPPERCASE",
        "ct.to_lower": "Convert to lowercase",
        "ct.remove_marks": "Remove diacritics",
        "ct.auto_paste": "Auto paste + select",
        "ct.caps_first": "Capitalize first letter",
        "ct.caps_each": "Capitalize Each Word",
        "ct.alert_done": "Alert when done",
        "ct.sequential": "Sequential convert",
        "ct.sequential_tooltip": "Press hotkey multiple times to cycle through options. Only available when 'Auto paste + select' is on.",
        "ct.options": "Options",
        "ct.clipboard": "Convert from Clipboard",
        "ct.choose_file": "Choose file",
        "ct.source_file": "Source file",
        "ct.no_file": "No file selected...",
        "ct.source_title": "Select source file",
        "ct.dest_file": "Destination file",
        "ct.dest_title": "Select destination file",
        "ct.hotkey_label": "Quick conversion hotkey:",
        "ct.encoding": "Code Table",
        "ct.source": "Source",
        "ct.dest": "Destination",
        "ct.swap": "Swap encoding",
        "ct.convert": "Convert",

        // ── About dialog (standalone) ──
        "a.title": "About VKey",
        "a.tagline": "Modern Vietnamese Input Method",
        "a.repo_vkey": "VKey Repo",
        "a.repo_openkey": "Original OpenKey Repo",
        "a.footer": "Powered by Sciter.JS for a smooth experience.",

        // ── App Overrides dialog ──
        "ao.title": "App Override",
        "ao.input_method": "Input method",
        "ao.encoding": "Encoding",
        "ao.send_method": "Send method",
        "ao.list_app": "Application",
        "ao.list_method": "Method",
        "ao.list_encoding": "Encoding",
        "ao.list_sendmethod": "Send method",
        "ao.app_ph": "e.g.: myapp.exe",

        // ── User Defined Input dialog ──
        "ud.title": "User-defined Input Method",
        "ud.key": "Key",
        "ud.action": "Action",
        "ud.apply": "Apply",
        "ud.clear_key": "Clear key",
        "ud.templates": "Templates:",
        "ud.group_tone": "Tone marks",
        "ud.group_circumflex": "Circumflex",
        "ud.group_horn": "Horn / Breve",
        "ud.group_stroke": "Stroke",
        "ud.group_special": "Special",
        "ud.group_insert": "Direct insertion",
        "ud.act.ClearTone": "Clear tone",
        "ud.act.ToneAcute": "Acute (s\u1eafc)",
        "ud.act.ToneGrave": "Grave (huy\u1ec1n)",
        "ud.act.ToneHook": "Hook (h\u1ecfi)",
        "ud.act.ToneTilde": "Tilde (ng\u00e3)",
        "ud.act.ToneDot": "Dot (n\u1eb7ng)",
        "ud.act.VniCircumflex": "Circumflex (\u00e2,\u00ea,\u00f4)",
        "ud.act.CircumflexA": "Circumflex for a \u2192 \u00e2",
        "ud.act.CircumflexE": "Circumflex for e \u2192 \u00ea",
        "ud.act.CircumflexO": "Circumflex for o \u2192 \u00f4",
        "ud.act.HornW": "Horn (\u0103,\u01b0,\u01a1)",
        "ud.act.HornInsertU": "Horn for u \u2192 \u01b0",
        "ud.act.HornInsertO": "Horn for o \u2192 \u01a1",
        "ud.act.VniHorn": "Horn (VNI 7) \u2192 \u01b0,\u01a1",
        "ud.act.VniBreve": "Breve for a \u2192 \u0103",
        "ud.act.HornOrInsertU": "Horn or insert \u01b0",
        "ud.act.HornOrInsertUNoStart": "Horn or \u01b0 (not at start)",
        "ud.act.StrokeD": "Stroke for d \u2192 \u0111",
        "ud.act.VniStroke": "Stroke (VNI 9)",
        "ud.act.UndoAllMarks": "Clear all marks",
        "ud.act.InsertABreve": "Letter \u0103",
        "ud.act.InsertABreveUpper": "Letter \u0102",
        "ud.act.InsertACircumflex": "Letter \u00e2",
        "ud.act.InsertACircumflexUpper": "Letter \u00c2",
        "ud.act.InsertDStroke": "Letter \u0111",
        "ud.act.InsertDStrokeUpper": "Letter \u0110",
        "ud.act.InsertECircumflex": "Letter \u00ea",
        "ud.act.InsertECircumflexUpper": "Letter \u00ca",
        "ud.act.InsertOCircumflex": "Letter \u00f4",
        "ud.act.InsertOCircumflexUpper": "Letter \u00d4",
        "ud.act.InsertOHorn": "Letter \u01a1",
        "ud.act.InsertOHornUpper": "Letter \u01a0",
        "ud.act.InsertUHorn": "Letter \u01b0",
        "ud.act.InsertUHornUpper": "Letter \u01af"
    }
};
